apiVersion: 1

datasources:
  - name: OpenSearch
    type: grafana-opensearch-datasource
    access: proxy
    uid: opensearch
    url: http://opensearch:9200
    editable: true
    jsonData:
      database: "*"
      timeField: time
      version: '2.8.0'

  - name: Jaeger
    type: jaeger
    uid: jaeger
    access: proxy
    url: http://jaeger:16686
    editable: true
